// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fcorp-dashboard/Dashboard.tsx": () => import("../components/mockups/fcorp-dashboard/Dashboard.tsx"),
  "./components/mockups/fcorp-screens/Dashboard.tsx": () => import("../components/mockups/fcorp-screens/Dashboard.tsx"),
  "./components/mockups/fcorp-screens/Squad.tsx": () => import("../components/mockups/fcorp-screens/Squad.tsx"),
  "./components/mockups/fcorp-screens/Tournament.tsx": () => import("../components/mockups/fcorp-screens/Tournament.tsx"),
  "./components/mockups/fcorp-screens/Transfers.tsx": () => import("../components/mockups/fcorp-screens/Transfers.tsx")
};
